name: Steam Workshop Update

on:
  push:
    branches:
      - main

jobs:
  update-steam-workshop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SteamCMD
        run: |
          sudo mkdir -p /steamcmd
          cd /steamcmd
          curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
          ./steamcmd.sh +login anonymous +quit

      - name: Get Latest Commit Message
        id: get_commit
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Update VDF File with Commit Message
        run: |
          sed -i 's/"changenote" ".*"/"changenote" "${COMMIT_MESSAGE}"/' /path/to/your/item.vdf

      - name: Upload Mod to Steam Workshop
        run: |
          cd /steamcmd
          ./steamcmd.sh +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +workshop_build_item /path/to/your/item.vdf +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

