name: Steam Workshop Update

on:
  push:
    branches:
      - main

jobs:
  update-steam-workshop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure Directory Permissions
        run: |
          sudo mkdir -p /steamcmd
          sudo chown $USER:$USER /steamcmd

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32gcc-s1 python3-pip

      - name: Install SteamCMD
        run: |
          cd /steamcmd
          curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
          ./steamcmd.sh +login anonymous +quit

      - name: Get Latest Commit Message
        id: get_commit
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Update VDF File with Commit Message
        run: |
          sed -i 's/"changenote" ".*"/"changenote" "${COMMIT_MESSAGE}"/' prisonrpcontentpackage.vdf

      - name: Install Steam Guard Code Generator
        run: |
          pip3 install steam

      - name: Generate Steam Guard Code
        id: steam_guard_code
        run: |
          from steam.guard import SteamAuthenticator
          import os
          shared_secret = os.getenv("STEAM_SHARED_SECRET")
          auth = SteamAuthenticator(shared_secret)
          code = auth.get_code()
          print(f"STEAM_GUARD_CODE={code}", file=open(os.getenv("GITHUB_ENV"), 'a'))
        env:
          STEAM_SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Upload Mod to Steam Workshop
        run: |
          cd /steamcmd
          ./steamcmd.sh +login "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" +authcode "${{ secrets.STEAM_GUARD_CODE }}" +workshop_build_item prisonrpcontentpackage.vdf +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
